In [1]:
import numpy as np #Problem 1

array1 = np.eye(3) * 9
print(array1)

[[9. 0. 0.]
 [0. 9. 0.]
 [0. 0. 9.]]


In [2]:
import numpy as np  #Problem 2

array2 = np.ones((7, 7))
array2[1:6, 1:6] = 0
array2[3, 3] = 5
print(array2)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 5. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


In [ ]:
import numpy as np #Problem 3

n = int(input())

array3 = np.arange(1, n+1)
array3 = np.tile(array3, (n, 1))

print(array3)

In [ ]:
import numpy as np #Problem 4

arr4 = np.random.randint(0, 101, (5, 5))
print(arr4)

print(np.max(arr4, axis=1))
print(np.sum(arr4, axis=0))
print(np.mean(arr4))

new_matrix = (arr4 > 50).astype(int)
print(new_matrix)

In [ ]:
import numpy as np #Problem 5

arr = np.arange(1, 31).reshape(6, 5)

print(arr[2:4, 0:2])
print(arr[[0,1,2,3], 1])
print(arr[::2])

In [ ]:
import numpy as np #Problem 6

scores = np.array([45, 88, 92, 30, 50, 76, 99, 12, 65])

print(scores[scores >= 50])
print(np.any(scores == 100))
print(np.all(scores >= 50))